CREATE TABLE AUDIT_TABLE(
    EVENT_TYPE VARCHAR2(30),
    LOGON_DATE DATE,
    LOGON_TIME VARCHAR2(20),
    LOGOFF_DATE DATE,
    LOGOF_TIME VARCHAR2(20)
);
    
CREATE OR REPLACE TRIGGER LOGIN_AUDIT
AFTER LOGON ON SCHEMA
BEGIN
    INSERT INTO AUDIT_TABLE VALUES(
    ORA_SYSEVENT,
    SYSDATE,
    TO_CHAR(SYSDATE, 'HH24:MI:SS'),
    SYSDATE,
    TO_CHAR(SYSDATE, 'HH24:MI:SS')
);
COMMIT;
END;
/

SELECT * FROM AUDIT_TABLE;