------------------------Procedure to drop all the tables in the database-----------------------


CREATE OR REPLACE PROCEDURE DROPTABLE(TABLE_NAME IN VARCHAR2) IS
BEGIN
 EXECUTE IMMEDIATE('DROP TABLE '||TABLE_NAME); 
EXCEPTION WHEN OTHERS THEN NULL;
END DROPTABLE;

call DROPTABLE('MUTUAL_FUND_TRANSACTIONS');
call DROPTABLE('MUTUAL_FUND_DETAILS');
call DROPTABLE('STOCK_TRANSACTIONS;');
call DROPTABLE('STOCK_DETAILS');
call DROPTABLE('FEEDBACK');
call DROPTABLE('CRYPTO_TRANSACTIONS');
call DROPTABLE('CRYPTO_DETAILS');
call DROPTABLE('FOREIGN_EXCHANGE_TRANSACTIONS');
call DROPTABLE('FOREIGN_EXCHANGE_DETAILS');
call DROPTABLE('CUSTOMER_FINANCIAL_DETAILS');
call DROPTABLE('CUSTOMER_DETAILS');

