CREATE TABLE CUSTOMER_DETAILS(
    CUSTOMER_ID NUMBER(10),
    CUSTOMER_NAME VARCHAR2(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    AGE NUMBER(2) NOT NULL,
    CONTACT NUMBER(10) NOT NULL,
    ZIP_CODE NUMBER(5) NOT NULL,
    STATE_NAME VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    PROFILE_CREATION_DATE DATE NOT NULL,
    CUSTOMER_PASSWORD VARCHAR2(8) NOT NULL,
    SECURITY_ANSWER1 VARCHAR2(15) NOT NULL,
    SECURITY_ANSWER2 VARCHAR2(15) NOT NULL,
    
    PRIMARY KEY(CUSTOMER_ID)
);


CREATE TABLE FOREIGN_EXCHANGE_TRANSACTIONS(
    FOREIGN_TRANSACTION_ID VARCHAR2(10),
    CURRENCY_ID VARCHAR2(10),
    CUSTOMER_ID VARCHAR2(10) NOT NULL,
    CURRENCY_TRANSACTION_DATE DATE NOT NULL,
    PURCHASED_CURRENCY_ID VARCHAR2(5) NOT NULL,
    MONEY_INVESTMENT_VALUE FLOAT(10) NOT NULL,
    PURCHASED_CURRENCY_VALUE FLOAT(10) NOT NULL,
    CURRENCY_TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    
    PRIMARY KEY(FOREIGN_TRANSACTION_ID),
    FOREIGN KEY (CURRENCY_ID)
    REFERENCES FOREIGN_EXCHANGE_DETAILS (CURRENCY_ID)
);

CREATE TABLE FOREIGN_EXCHANGE_DETAILS(
    CURRENCY_ID VARCHAR(10),
    CURRENCY_NAME VARCHAR2(40) NOT NULL,
    CURRENCY_COUNTRY VARCHAR2(40) NOT NULL,
    CURRENCY_ISO VARCHAR2(5) NOT NULL,
    CURRENCY_CURRENT_PRICE FLOAT(10) NOT NULL,
    
    PRIMARY KEY(CURRENCY_ID)
);